#! /bin/bash

set -e

if [[ -z "$DEV" ]]; then echo "Missing Device name" && exit; fi

DEV_CAP=$(nvme zns report-zones /dev/$DEV -d 1 | grep -o 'Cap:.*$' | awk '{print strtonum($2)}')
DEV_ZONE_SIZE=$(cat /sys/block/$DEV/queue/chunk_sectors)
DEV_ZONES=$(cat /sys/block/$DEV/queue/nr_zones)
DEV_MAX_ACTIVE_ZONES=$(cat /sys/block/$DEV/queue/max_active_zones)

echo $DEV_CAP $DEV_ZONE_SIZE $DEV_ZONES $DEV_MAX_ACTIVE_ZONES
