#! /bin/bash

set -e

DEV_CAP=$(nvme zns report-zones /dev/$DEV -d 1 | grep -o 'Cap:.*$' | awk '{print strtonum($2)*512}')
DEV_ZONES=$(cat /sys/block/$DEV/queue/nr_zones)
DEV_ACTIVE_ZONES=$(cat /sys/block/$DEV/queue/max_active_zones)

export $DEV_CAP
export $DEV_ZONES
export $DEV_ACTIVE_ZONES
