#! /bin/bash

set -e

if [[ "$#" -ne "1" ]]; then echo "Requires device name (e.g. nvme2n2) argument" && exit; fi

DEV=$1
ZONED=0
PARTITION=0

if [[ ! -z "$(echo $DEV | grep -E 'nvme[0-9]+n[0-9]+p[0-9]+')" ]]; then
    # Using parition instead of namespace, have to find info differently
    DEV_SECT_SIZE=$(cat /sys/block/$(echo "$DEV" | sed 's/p[0-9]*//')/queue/hw_sector_size)
    DEV_NUMA_NODE=$(cat /sys/block/$(echo "$DEV" | sed 's/p[0-9]*//')/device/numa_node)
    DEV_SIZE=$(cat /sys/block/$(echo "$DEV" | sed 's/p[0-9]*//')/$DEV/size)
    ZONED=0
    PARTITION=1

    export DEV_SIZE

elif [[ "$(cat /sys/block/$DEV/queue/zoned)" == "host-managed" ]]; then
    # Get the device information
    DEV_INFO=($(./get_zoned_device_info $DEV | awk 'NF{ print $NF }'))

    DEV_ZONE_CAP=${DEV_INFO[0]}
    DEV_ZONE_SIZE=${DEV_INFO[1]}
    DEV_ZONES=${DEV_INFO[2]}
    DEV_MAX_ACTIVE_ZONES=${DEV_INFO[3]}
    DEV_SECT_SIZE=${DEV_INFO[4]}
    DEV_SCHEDULER=${DEV_INFO[5]}
    DEV_NUMA_NODE=${DEV_INFO[6]}
    ZONED=1

    export DEV_ZONE_CAP
    export DEV_ZONE_SIZE
    export DEV_ZONES
    export DEV_MAX_ACTIVE_ZONES
    export DEV_SCHEDULER
else
    # Device is not zoned device
    DEV_SECT_SIZE=$(cat /sys/block/$DEV/queue/hw_sector_size)
    DEV_NUMA_NODE=$(cat /sys/block/$DEV/device/numa_node)
    DEV_SIZE=$(cat /sys/block/$DEV/size)
    ZONED=0

    export DEV_SIZE
fi

export DEV
export ZONED
export DEV_SECT_SIZE
export DEV_NUMA_NODE
export PARTITION

PS3=$(printf "\nEnter the number for the benchmark to run: ")
BENCHMARKS=("fio_throughput" "fio_scaled_bandwidth" "fio_active_zones" "fio_concur_write_seq")

select benchmark in "${BENCHMARKS[@]}"
do
    if [[ -z "$benchmark" ]]; then
        echo "Invalid Input."
    elif [[ "$benchmark" == "${BENCHMARKS[0]}" ]]; then
        echo "Running fio_throughput benchmark"
        numactl -m $DEV_NUMA_NODE IO_Performance/fio_throughput
        break
    elif [[ "$benchmark" == "${BENCHMARKS[1]}" ]]; then
        echo "Running fio_scaled_bandwidth benchmark"
        numactl -m $DEV_NUMA_NODE IO_Performance/fio_scaled_bandwidth
        break
    elif [[ "$benchmark" == "${BENCHMARKS[2]}" ]]; then
        echo "Running fio_active_zones benchmark"
        [[ "$ZONED" == "1" ]] && numactl -m $DEV_NUMA_NODE IO_Performance/fio_active_zones || "Can only run fio_active_zones with a zoned device"
        break
    elif [[ "$benchmark" == "${BENCHMARKS[3]}" ]]; then
        echo "Running fio_concur_write_seq benchmark"
        numactl -m $DEV_NUMA_NODE IO_Performance/fio_concur_write_seq
        break
    fi
done
