#! /bin/bash

set -e

DATA_DIR="IO_Performance/data/active_zones/$DEV-$(date +"%Y_%m_%d_%I_%M_%p")"
SIZE=$(echo "scale=0;$DEV_ZONE_SIZE*$DEV_SECT_SIZE*$DEV_ZONES" | bc)
ACTIVE_ZONES=($(seq 1 1 $DEV_MAX_ACTIVE_ZONES))
QUEUE_DEPTH="16"
RUNTIME="30s"
BS="4Ki"
RAMP_TIME="10s"

mkdir -p $DATA_DIR
cd $DATA_DIR

# Run fio for each active zone setup
for zones in ${ACTIVE_ZONES[@]}; do
    echo "Running benchmarks with number of active zones: $zones"
    blkzone reset /dev/$DEV # make sure ns is empty

    fio --name=$(echo "${DEV}_randwrite_${BS}_active-zones-${zones}") --output=$(echo "${DEV}_randwrite_${BS}_active-zones-${zones}.json") --output-format=json --filename=/dev/$DEV --direct=1 --size=$SIZE --ioengine=libaio --zonemode=zbd --iodepth=$QUEUE_DEPTH --rw=randwrite --bs=$BS --max_open_zones=$zones --runtime=$RUNTIME --numa_cpu_nodes=$DEV_NUMA_NODE --ramp_time=$RAMP_TIME

    # Fill entire ns for reading and overwrite
    echo "Refilling entire namespace for read/overwrite benchs"
    fio --name=zns-fio --filename=/dev/$DEV --direct=1 --size=$SIZE --ioengine=libaio --zonemode=zbd --iodepth=4 --rw=write --bs=512K > /dev/null

    fio --name=$(echo "${DEV}_randread_${BS}_active-zones-${zones}") --output=$(echo "${DEV}_randread_${BS}_active-zones-${zones}.json") --output-format=json --filename=/dev/$DEV --direct=1 --size=$SIZE --ioengine=libaio --zonemode=zbd --iodepth=$QUEUE_DEPTH --rw=randread --bs=$BS --max_open_zones=$zones --runtime=$RUNTIME --numa_cpu_nodes=$DEV_NUMA_NODE --ramp_time=$RAMP_TIME
    fio --name=$(echo "${DEV}_randoverwrite_${BS}_active-zones-${zones}") --output=$(echo "${DEV}_randoverwrite_${BS}_active-zones-${zones}.json") --output-format=json --filename=/dev/$DEV --direct=1 --size=$SIZE --ioengine=libaio --zonemode=zbd --iodepth=$QUEUE_DEPTH --rw=randwrite --bs=$BS --max_open_zones=$zones --runtime=$RUNTIME --numa_cpu_nodes=$DEV_NUMA_NODE --ramp_time=$RAMP_TIME
done
