#! /bin/bash

set -e

if [[ "$#" -ne "1" ]]; then echo "Requires device name (e.g. nvme2n2) argument" && exit; fi

DATA_DIR="data/bandwidth"
QUEUE_DEPTHS=(1 2 4 8 16 32 64 128 256 512 1024)
# fio would stop once ns is full hence we use zone size instead of capacity
SIZE=$(echo "scale=0;$DEV_ZONE_SIZE*512*$DEV_ZONES" | bc)
RUNTIME="10m"

mkdir -p $DATA_DIR
cd $DATA_DIR

for depth in ${QUEUE_DEPTHS[@]}; do
    echo "Running benchmarks with Queue Depth: $depth"
    blkzone reset /dev/$DEV # make sure ns is empty
    fio --name=$(echo "${DEV}_randwrite_512B_queue-depth-${depth}") --output=$(echo "${DEV}_randwrite_512B_queue-depth-${depth}") --output-format=json --filename=/dev/$DEV --direct=1 --size=$SIZE --ioengine=libaio --zonemode=zbd --iodepth=$depth --rw=randwrite --bs=512 --max_open_zones=$DEV_MAX_ACTIVE_ZONES --runtime=$RUNTIME
    blkzone reset /dev/$DEV # make sure ns is empty
    fio --name=$(echo "${DEV}_write_512B_queue-depth-${depth}") --output=$(echo "${DEV}_write_512B_queue-depth-${depth}") --output-format=json --filename=/dev/$DEV --direct=1 --size=$SIZE --ioengine=libaio --zonemode=zbd --iodepth=$depth --rw=write --bs=512 --runtime=$RUNTIME

    # Fill entire ns for reading
    fio --name=zns-fio --filename=/dev/$DEV --direct=1 --size=$SIZE --ioengine=libaio --zonemode=zbd --iodepth=4 --rw=write --bs=512K > /dev/null

    fio --name=$(echo "${DEV}_read_512B_queue-depth-${depth}") --output=$(echo "${DEV}_read_512B_queue-depth-${depth}") --output-format=json --filename=/dev/$DEV --direct=1 --size=$SIZE --ioengine=libaio --zonemode=zbd --iodepth=$depth --rw=read --bs=512 --runtime=$RUNTIME
    fio --name=$(echo "${DEV}_randread_512B_queue-depth-${depth}") --output=$(echo "${DEV}_randread_512B_queue-depth-${depth}") --output-format=json --filename=/dev/$DEV --direct=1 --size=$SIZE --ioengine=libaio --zonemode=zbd --iodepth=$depth --rw=randread --bs=512 --runtime=$RUNTIME
    fio --name=$(echo "${DEV}_overwrite-seq_512B_queue-depth-${depth}") --output=$(echo "${DEV}_overwrite-seq_512B_queue-depth-${depth}") --output-format=json --filename=/dev/$DEV --direct=1 --size=$SIZE --ioengine=libaio --zonemode=zbd --iodepth=$depth --rw=write --bs=512 --runtime=$RUNTIME
    fio --name=$(echo "${DEV}_overwrite-rand_512B_queue-depth-${depth}") --output=$(echo "${DEV}_overwrite-rand_512B_queue-depth-${depth}") --output-format=json --filename=/dev/$DEV --direct=1 --size=$SIZE --ioengine=libaio --zonemode=zbd --iodepth=$depth --rw=randwrite --bs=512 --max_open_zones=$DEV_MAX_ACTIVE_ZONES --runtime=$RUNTIME
done
