#! /bin/bash

set -e

DATA_DIR="IO_Performance/data/concur_write_seq_iodepth/$DEV-$(date +"%Y_%m_%d_%I_%M_%p")"
SIZE="3z"
MQ_SIZE=$(echo "scale=0;$DEV_ZONE_SIZE*$DEV_SECT_SIZE*$DEV_ZONES" | bc)
OFF_INC="3z"
NUMJOBS=($(seq 1 1 $DEV_MAX_ACTIVE_ZONES))
RUNTIME="30s"
BS="4Ki"
RAMP_TIME="10s"

mkdir -p $DATA_DIR
cd $DATA_DIR

# Run fio for each active zone setup
for jobs in ${NUMJOBS[@]}; do
    echo "Running benchmarks with number of jobs: $jobs"
    blkzone reset /dev/$DEV # make sure ns is empty

    # set mq-deadline scheduler
    echo mq-deadline | tee /sys/block/nvme2n2/queue/scheduler > /dev/null

    fio --name=$(echo "${DEV}_mq-deadline_${BS}_iodepth-${jobs}") --output=$(echo "${DEV}_mq-deadline_${BS}_numjobs-${jobs}.json") --output-format=json --filename=/dev/$DEV --direct=1 --size=$MQ_SIZE --ioengine=libaio --zonemode=zbd --rw=write --bs=$BS --runtime=$RUNTIME --numa_cpu_nodes=$DEV_NUMA_NODE --ramp_time=$RAMP_TIME --iodepth=$jobs --time_based --percentile_list=50:95:99:99.9:99.99:99.999:99.9999:99.99999:100

    blkzone reset /dev/$DEV # make sure ns is empty

    # set none scheduler
    echo none | tee /sys/block/nvme2n2/queue/scheduler > /dev/null

    fio --name=$(echo "${DEV}_none_${BS}_nummjobs-${jobs}") --output=$(echo "${DEV}_none_${BS}_numjobs-${jobs}.json") --output-format=json --filename=/dev/$DEV --direct=1 --size=$SIZE --offset_increment=$OFF_INC --ioengine=psync --zonemode=zbd --rw=write --bs=$BS --runtime=$RUNTIME --numa_cpu_nodes=$DEV_NUMA_NODE --ramp_time=$RAMP_TIME --numjobs=$jobs --time_based --group_reporting --percentile_list=50:95:99:99.9:99.99:99.999:99.9999:99.99999:100
done
