#! /bin/bash

set -e

if [[ "$#" -ne "1" ]]; then echo "Requires device name (e.g. nvme2n2) argument" && exit; fi

DEV=$1

# Get the device information
DEV_INFO=($(../get_device_info $DEV | awk 'NF{ print $NF }'))

DEV_ZONE_CAP=${DEV_INFO[0]}
DEV_ZONE_SIZE=${DEV_INFO[1]}
DEV_ZONES=${DEV_INFO[2]}
DEV_MAX_ACTIVE_ZONES=${DEV_INFO[3]}
DEV_SECT_SIZE=${DEV_INFO[4]}
DEV_SCHEDULER=${DEV_INFO[5]}
DEV_NUMA_NODE=${DEV_INFO[6]}

export DEV
export DEV_ZONE_CAP
export DEV_ZONE_SIZE
export DEV_ZONES
export DEV_MAX_ACTIVE_ZONES
export DEV_SECT_SIZE
export DEV_SCHEDULER
export DEV_NUMA_NODE

# ./fio_bandwidth
# ./fio_active_zones
